import { PostWithImage } from "@/components/PostWithImage/PostWithImage";
import { PostFromDbProps } from "@/firebase/db";
import { useGetMyFeed } from "@/hooks/useGetMyFeed";
import {
  Card,
  CardContent,
  Divider,
  LinearProgress,
  Typography,
  useTheme,
} from "@mui/material";
import Head from "next/head";
import React from "react";
import { Gallery } from "../Gallery/Gallery";
import { TabPanel } from "../TabPanel/TabPanel";

export const Feed: React.FC = () => {
  const { data, isLoading, error } = useGetMyFeed("max");
  if (!data || isLoading) {
    return <LinearProgress style={{ width: "100%" }} />;
  }
  console.log('zyz', data)
  
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data?.length === 0 && (
          <Card>
            <CardContent>
              <Typography>
                {" You're currently not following anyone"}
              </Typography>
            </CardContent>
          </Card>
        )}
        <TabPanel value={0} index={0}>
          <Gallery posts={data} mode="column" />
        </TabPanel>
      </div>
      <div style={{ height: "50px" }} />
    </div>
  );
};
