import { useAuth } from "@/context/AuthContext";
import { useGetMyFeed } from "@/hooks/useGetMyFeed";
import { useGetUserInfo } from "@/hooks/useGetUserInfo";
import { Card, CardContent, LinearProgress, Typography } from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { Gallery } from "../Gallery/Gallery";
import { TabPanel } from "../TabPanel/TabPanel";

export const Feed: React.FC = () => {
  const auth = useAuth();
  const router = useRouter();
  if (!auth?.isLoggedIn) {
    router.push("/signin");
  }

  const userInfoRes = useGetUserInfo(auth?.uid || "");
  console.log('infeed', userInfoRes)
  const feedRes = useGetMyFeed(userInfoRes?.data?.username);
  React.useEffect(() => {}, [auth?.isLoggedIn, feedRes.isLoading]);
  if (!userInfoRes.data && feedRes?.isLoading) {
    return <LinearProgress style={{ width: "100%" }} />;
  }
  if (!feedRes?.data) {
    return (
      <Card>
        <CardContent>
          <Typography>{" You're currently not following anyone"}</Typography>
        </CardContent>
      </Card>
    );
  }

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <TabPanel value={0} index={0}>
          <Gallery posts={feedRes.data || []} mode="column" />
        </TabPanel>
      </div>
      <div style={{ height: "50px" }} />
    </div>
  );
};
