import { Gallery } from "@/components/Gallery/Gallery";
import { ProfileButtons } from "@/components/ProfileButtons/ProfileButtons";
import { ProfileHeader } from "@/components/ProfileHeader/ProfileHeader";
import { TabPanel } from "@/components/TabPanel/TabPanel";
import { useAuth } from "@/context/AuthContext";
import { getPostByUsername, getUsername, PostFromDbProps } from "@/firebase/db";
import {
  Button,
  Card,
  CardContent,
  Divider,
  Typography,
  useTheme,
} from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

export async function getServerSideProps({
  params,
}: {
  params: { username: string };
}) {
  const { username } = params;
  const uid = await getUsername(username);
  if (!uid) {
    return {
      props: { error: { code: 4, message: "Broken page" } },
    };
  }
  const posts = await getPostByUsername(username);
  return {
    props: {
      posts,
      uid, 
      username
    },
  };
}

interface ProfileProps {
  posts: PostFromDbProps[];
  uname: {uid: string};
  username: string;
  error: { code: number; message: string };
}

export const Profile: React.FC<ProfileProps> = ({ posts, error, uname, username }) => {
  const [value, setValue] = React.useState(0);
  const theme = useTheme();
  const router = useRouter();
  const auth = useAuth();
  const uid = auth?.uid || ""

  if (error?.code == 4) {
    return (
      <div>
        <Card>
          <Typography>Broken page</Typography>
        </Card>
      </div>
    );
  }

  const handleChange = (event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };

  const hasNoPosts = posts.length === 0 && (uname?.uid == uid)
  const makePost = (
    <Card sx={{margin: 2}}>
      <CardContent>
        <Typography>It feels so empty here. Make a post!</Typography>
        <Button
        fullWidth
        sx={{marginTop: 1}}
        variant='contained'
          onClick={() => {
            router.push("/add-post");
          }}
        >
          Make a post
        </Button>
      </CardContent>
    </Card>
  );

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileHeader />
      <Divider sx={{ width: "100%" }} />
      {hasNoPosts && makePost}
      {!hasNoPosts && (
        <>
          <ProfileButtons handleChange={handleChange} value={value} />
          <TabPanel value={value} index={0} dir={theme.direction}>
            <Gallery mode="column" posts={posts} />
          </TabPanel>
          <TabPanel value={value} index={1} dir={theme.direction}>
            <Gallery mode="grid" posts={posts} />
          </TabPanel>
        </>
      )}
    </>
  );
};

export default Profile;
