import React from "react";
import Head from "next/head";
import styles from "../styles/AddPost.module.css";
import { AddPostContainer } from "@/components/AddPostContainer/AddPostContainer";
import { AddPostContextWrapper } from "@/context/AddPostContext";
import { addDoc, collection, doc, setDoc, getDoc } from "firebase/firestore";
import{firestore} from '../firebase/clientApp'
export async function getServerSideProps(context) {
  console.log('we run')
  const docRef = doc(firestore, "cities", "SF");
  const docSnap = await getDoc(docRef);
  
  if (docSnap.exists()) {
    console.log("Document data:", docSnap.data());
  } else {
    // doc.data() will be undefined in this case
    console.log("No such document!");
  }
  

  return {
    props: {}, // will be passed to the page component as props
  }
}

const AddPost = () => {
  return (
    <>
      <Head>
        <title>Add Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AddPostContextWrapper>
          <AddPostContainer />
        </AddPostContextWrapper>
      </main>
    </>
  );
};
export default AddPost;
