import React from "react";
import Head from "next/head";
import { AddPostContainer } from "@/components/AddPostContainer/AddPostContainer";
import { AddPostContextWrapper } from "@/context/AddPostContext";
import { AuthContext } from "@/context/AuthContext";
import { useRouter } from "next/router";

const AddPost = () => {
  const {user} = React.useContext(AuthContext);
  const router = useRouter();

  React.useEffect(() => {
    if(!user?.uid){
      router.push('/signin')
    } 
  }, [])
  return (
    <>
      <Head>
        <title>Add Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <AddPostContextWrapper>
          <AddPostContainer />
        </AddPostContextWrapper>
    </>
  );
};
export default AddPost;
