import React from "react";
import Head from "next/head";
import styles from "../styles/AddPost.module.css";
import { AddPostContainer } from "@/components/AddPostContainer/AddPostContainer";
import { AddPostContextWrapper } from "@/context/AddPostContext";

const AddPost = () => {
  return (
    <>
      <Head>
        <title>Add Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AddPostContextWrapper>
          <AddPostContainer />
        </AddPostContextWrapper>
      </main>
    </>
  );
};
export default AddPost;
