'use client';

import Head from "next/head";
import React from "react";

import { useAuth } from "@/context/AuthContext";
import { Card, CardContent, LinearProgress, Typography } from "@mui/material";
import { CreateUsername } from "@/components/CreateUsername/CreateUsername";
import { useGetUserInfo } from "@/hooks/useGetUserInfo";
import { Feed } from "@/components/Feed/Feed";


export default function Home() {
  const auth = useAuth();
  
  const { data, isLoading } = useGetUserInfo(auth?.user?.uid as string);
  const noUserName = !auth.isLoading && !isLoading && !data?.username
  if(isLoading){
    return <LinearProgress sx={{width: '100%'}}/>
  }

 
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        width: '100%'
      }}
    >
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <div
        style={{
          display: "flex",
          width: "100%",
          flexDirection: "column",
        }}
      >
          <div style={{ padding: "8px" }}>
        {(noUserName) && <CreateUsername />}
      </div>
        <Feed />
      </div>
    </div>
  );
}
