import Head from 'next/head'
import React from 'react';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { AuthContext } from '@/context/AuthContext'
const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const authContext = React.useContext(AuthContext)
  console.log(authContext)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main className={styles.main}>
      
      </main>
    </>
  )
}
