import { Gallery } from "@/components/Gallery/Gallery";
import { Links } from "@/components/Links/Links";
import { ProfileButtons } from "@/components/ProfileButtons/ProfileButtons";
import { ProfileStats } from "@/components/ProfileStats/ProfileStats";
import { TabPanel } from "@/components/TabPanel/TabPanel";
import { sampleId } from "@/constants/sampledId";
import {  PostFromDbProps } from "@/firebase/db";
import { useGetPostsByUid } from "@/hooks/useGetPostsByUid";
import {
  Avatar,
  Divider,
  useTheme,
} from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

// sample profile
interface ProfileProps {
  posts: PostFromDbProps[];
  uname: { uid: string };
  username: string;
  error: { code: number; message: string };
}

export const SampleProfile: React.FC<ProfileProps> = () => {
  const [value, setValue] = React.useState(0);
  const theme = useTheme();
  const router = useRouter();
  const usernameInPath = router.query.username || "";
  const postRes: {
    posts: PostFromDbProps[];
    error: any;
    isLoading: boolean;
  } = useGetPostsByUid(sampleId);

  const handleChange = (event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          width: "100%",
          padding: "0px 16px 4px 16px",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <div
          style={{
            display: "flex",
            width: "100%",
            justifyContent: "center",
            alignItems: "center",
          }}
        ></div>
        <div style={{ display: "flex", alignItems: "center" }}>
          <div>
            <Avatar
              src={""}
              style={{ marginRight: "8px", height: 90, width: 90 }}
            ></Avatar>
          </div>
          <ProfileStats posts={224} following={812} followers={47} />
        </div>
        <div style={{ margin: "8px 0px 8px 0" }}>
        </div>
      </div>
      <Divider sx={{ width: "100%" }} />
      {
        <>
          <ProfileButtons handleChange={handleChange} value={value} />
          <TabPanel value={value} index={0} dir={theme.direction}>
            <Gallery posts={postRes.posts} mode="column" />
          </TabPanel>
          <TabPanel value={value} index={1} dir={theme.direction}>
            <Gallery mode="grid" posts={postRes.posts} />
          </TabPanel>
          <TabPanel value={value} index={2} dir={theme.direction}>
            <Links username={usernameInPath as string} />
          </TabPanel>
        </>
      }
      <div style={{ height: "50px" }} />
    </>
  );
};

export default SampleProfile;
