import Head from "next/head";
import React from "react";

import { useAuth } from "@/context/AuthContext";
import {
  Avatar,
  Card,
  CardContent,
  LinearProgress,
  TextField,
  Typography,
} from "@mui/material";
import { CreateUsername } from "@/components/CreateUsername/CreateUsername";
import { useGetUserInfo } from "@/hooks/useGetUserInfo";
import { SearchContainer } from "@/components/SearchContainer/SearchContainer";
import { useGetAllUsernames } from "@/hooks/useGetAllUsernames";
import { SearchResultUser } from "@/components/SearchResultUser/SearchResultUser";

export default function Search() {
  const auth = useAuth();
  const [text, setText] = React.useState("");
  const usernames = useGetAllUsernames();
  const users = usernames?.data?.map((user) => <SearchResultUser key={user.id} username={user.id}/>)
  
  const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setText(e.target.value);
  };
  const { data, error, isLoading } = useGetUserInfo(auth?.uid as string);
  console.log(data);
  if (isLoading) {
    return <LinearProgress />;
  }
  return (
    <div
      style={{
        height: "100%",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        width: '100%'
      }}
    >
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          width: '100%',
          height: '100%',
          padding: "8px",
        }}
      >
        <TextField
          fullWidth
          onChange={onChange}
          value={text}
          variant="outlined"
          placeholder={"Search"}
        />
        <div style={{marginTop:'8px'}}>

        {users}
        </div>
      </div>
    </div>
  );
}
