import React from "react";
import Head from "next/head";
import { SignInNewUser } from "@/components/SignInNewUser/SignInNewUser";
import { useAuth } from "@/context/AuthContext";

const SignIn = () => {
  const auth = useAuth();
  return (
    <>
      <Head>
        <title>Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ display: "flex", width: "100%", height: "100%" }}>
        <SignInNewUser />
      </main>
    </>
  );
};
export default SignIn;
