import React from "react";
import Head from "next/head";
import styles from "../styles/AddPost.module.css";
import { AddPostContainer } from "@/components/AddPostContainer/AddPostContainer";
import { AddPostContextWrapper } from "@/context/AddPostContext";
import { SignInNewUser } from "@/components/SignInNewUser/SignInNewUser";

const SignIn = () => {
  return (
    <>
      <Head>
        <title>Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SignInNewUser/>
      </main>
       
    </>
  );
};
export default SignIn;
